### ISSUE TITLE
Database name being ignored

### ISSUE THREAD

**Issue by DrValani** [EqualExperts/dbt-unit-testing#68]
I get the following error when running unit tests from a different database. 

Suppose I am running a unit test from project "project_A", but my source data is from "project_B then I get the following error:

`404 Not found: Dataset projectId_A:my_dataset was not found in location EU`

In `sources.yml` we define sources from different databases, ie:

```
  - name: my_dataset
    database: project_B
    tables:
      - name: <table_name>
```

I have installed:

  - git: "https://github.com/EqualExperts/dbt-unit-testing"
    revision: v0.1.0
